### ISSUE TITLE
Automattic Syncing of Permissions Breaks

### ISSUE THREAD

**Issue by nZac** [level12/keg-auth#57]
Automatic syncing of permissions doesn't seem to like it when you use a `pool_pre_ping` on the engine.

```python
Traceback (most recent call last):
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/sqlalchemy/util/_collections.py", line 988, in __call__
    return self.registry[key]
KeyError: 4348003776

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 ... clipped a bunch of click stuff

  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg/cli.py", line 44, in list_commands
    info.load_app()
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/flask/cli.py", line 229, in load_app
    rv = self.create_app(self)
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg/cli.py", line 332, in create_app
    return self.appcls().init(**init_kwargs)
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg/app.py", line 98, in init
    self.on_init_complete()
  File "/Users/nzac/j/level12/clients/racebetter/src/racebetter/app.py", line 55, in on_init_complete
    rbext.auth_manager.init_app(self)
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg_auth/core.py", line 78, in init_app
    self.init_permissions(app)
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg_auth/core.py", line 199, in init_permissions
    sync_permissions()
  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/keg_auth/core.py", line 158, in sync_permissions
    db_permissions = db.session.query(Permission).all()

...  clip a bunch of sa stuff

  File "/Users/nzac/.pyenv/versions/3.5.2/envs/racebetter/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 160, in create
    engineclass.__name__))
TypeError: Invalid argument(s) 'pool_pre_ping' sent to create_engine(), using configuration PGDialect_psycopg2/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

**Comment by nZac** [comment]
There is a good chance this is not a KA issue but an app issue. Syncing permissions just showed it first.
